name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH and Update Known Hosts
        run: |
          set -x
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts
        shell: /usr/bin/bash -e {0}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST_IP: ${{ secrets.EC2_IP }}

      - name: Sync changes to EC2
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_rsa" --exclude=node_modules --exclude=.git ./ ${{ secrets.EC2_IP_ADDRESS }}:~/book-library-tool
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_IP_ADDRESS }} "cd ~/book-library-tool && npm install && sudo systemctl restart myapp.service"
